### ISSUE TITLE
[ISSUE] Can't get followers more than 2000

### ISSUE THREAD

**Issue by mustafahakkoz** [drawrowfly/twitter-scraper-bot#1]
Firstly i want to say it's a great app, overall well done. I can get tweets, user infos, followers just in matter of seconds. But it seems like there's a limit for it.

When i tried to get followers of someone, it works great until "-n 2000" and it gets stucks for more.
I run example code with 2001
`$ twitter-buddy followers realDonaldTrump -u TWITTER_USERNAME -p TWITTER_PASSWORD -n 2001`
and it is continuing scraping forever. I've waited for hours but no error or anything displaying just "Scraping user followers data". Limitation number may not be exact, may change day to day, but in my case it was 2000 and app didn't accept request even for +1. I checked it with other usernames and accounts  also.

tweeter-buddy v1.03
npm v6.12.0
node v12.13.0
Windows 7 64 bit
 
EDIT: Weirdly, today's limit is 1416 for all usernames. It seems like twitter sets some limit for my IP, depending on their mood for the day.

**Comment by drawrowfly** [comment]
Hi

I will take a look at the issue within next few days
